version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodejs-aws-codedeploy-pipeline
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root
      environment:
        BRANCH_NAME: "{{BRANCH_NAME}}"
    - location: scripts/application_start.sh
      timeout: 600
      runas: root
