version: 0.2
env:
  variables:
    CURRENT_ENVIRONMENT: $BRANCH_NAME
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing
  pre_build:
    commands:

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Creating branch txt that will be used for appspec.yml for the creation of environement variable stored on system manager ...
      - echo "${BRANCH_NAME}" >> envfile
artifacts:
  files:
    - envfile
    - '**/*'